### ISSUE TITLE
Egenmeldt sykefravær (RA-0182)

### ISSUE THREAD

**Issue by Halland67** [Altinn/app-migration#105]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | 4 |
| **Tjenesteutgavekode**  | 2437 |
| **Tjenestetype**  | Innsending  |
| **Volum**  | 10 000 transaksjoner pr år |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [X] Ja
- [ ] Nei

_4 ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
- [ ] https://github.com/Altinn/app-frontend-react/issues/717
- [ ] https://github.com/Altinn/app-frontend-react/issues/504
- [ ] https://github.com/Altinn/app-frontend-react/issues/883
- [ ] https://github.com/Altinn/altinn-studio/issues/8279

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 25.08.23
