### ISSUE TITLE
Næringsundersøkelse for Svalbard (RA-0657)

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-migration#106]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | 4440  |
| **Tjenesteutgavekode**  |  3 |
| **Tjenestetype**  | Innsending  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | SFTP |
 

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [X] Ja
- [ ] Nei

_Årlig - slutten av mai hvert år - frist sette igjennom prefill._

## Skjermbilder
![image](https://user-images.githubusercontent.com/43333852/193281132-87967ed8-edff-4897-ac25-ff6030d9d713.png)
![image](https://user-images.githubusercontent.com/43333852/193281213-1c573336-1603-43a9-abd3-c688b1508c16.png)

## Behov for funksjonalitet

-  Behov for "regnestykke-komponenten" som ligger i FIGMA (finner ingen ISSUE på denne??)
![image](https://user-images.githubusercontent.com/43333852/193281548-a4d4bb6c-4dfb-46fa-b0dc-556691b78e25.png)

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |  |
| Altinn 2.0 (test)  | [https://tt02.altinn.no/ ....](https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=3&ServiceCode=4440) |
| Altinn 2.0 (prod)  |   |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 14.12.22
