### ISSUE TITLE
Medlemstall og arbeidskonflikter (RA-0244)

### ISSUE THREAD

**Issue by Halland67** [Altinn/app-migration#107]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** |4790  |
| **Tjenesteutgavekode**  |  1|
| **Tjenestetype**  | Innsending |
| **Volum**  | 95  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [X] Ja
- [ ] Nei

_Frist settes gjennom prefill, årlig utsending i februar_

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
- [ ] https://github.com/Altinn/app-frontend-react/issues/530
- [ ] https://github.com/Altinn/app-frontend-react/issues/516
- [ ] https://github.com/Altinn/app-frontend-react/issues/883
- [ ] https://github.com/Altinn/app-frontend-react/issues/504
- [ ] https://github.com/Altinn/app-frontend-react/issues/717
- [ ] https://github.com/Altinn/app-frontend-react/issues/726
- [ ] https://github.com/Altinn/altinn-studio/issues/8279
- [ ] https://github.com/Altinn/app-frontend-react/issues/1098
- [ ] https://github.com/Altinn/app-frontend-react/issues/1111
- [ ] https://github.com/Altinn/app-frontend-react/issues/1112

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by StianVestli** [comment]
https://github.com/Altinn/app-frontend-react/issues/516

**Comment by StianVestli** [comment]
https://github.com/Altinn/altinn-studio/issues/9070

**Comment by elwal** [comment]
Produksjonssatt 28.08.23
