### ISSUE TITLE
Bruk av IKT i næringslivet (RA-0419)

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-migration#117]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | _Legg inn tjenestekode (ServiceCode)_  |
| **Tjenesteutgavekode**  |  _Legg inn tjenesteutgavekode (ServiceEditionCode)_ |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [ ] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
- [ ] https://github.com/Altinn/app-frontend-react/issues/583
- [ ] https://github.com/Altinn/app-frontend-react/issues/504
- [ ] https://github.com/Altinn/app-frontend-react/issues/883
- [ ] https://github.com/Altinn/app-frontend-react/issues/726
- [ ] https://github.com/Altinn/app-frontend-react/issues/603
- [ ] https://github.com/Altinn/altinn-studio/issues/8279

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Las
[RA-0419_M_4958_47423_SERES.zip](https://github.com/Altinn/app-migration/files/10390121/RA-0419_M_4958_47423_SERES.zip)
t opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.studio/editor/ttd/ra-0419 |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 26.01.24
