### ISSUE TITLE
Årlig melding for godkjent renholdsvirksomhet

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/app-migration#12]
## Innledning

> Alle godkjente renholdsvirkosmheter skal hvert år sende melding til Arbeidstilsynet som bekrefter at virksomheten fortsatt fyller kravene til godkjenning etter forskriften § 5. Virksomheter som er godkjent med ansatte skal hvert tredje år sende dokumentasjon som viser at virksomheten fortsatt fyller kravene til godkjenning etter § 5. Dokumentasjonen skal første gang sendes innen tre år fra datoen for vedtaket om godkjenning og senere innen tre år fra den forrige fristdatoen. Du bekrefter at virksomheten fortsatt fyller kravene til godkjenning etter § 5 ved å fylle ut og sende inn dette skjemaet. Dersom du har fått brev om å sende dokumentasjon skal du sende dette sammen med skjemaet.

#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Ny tjeneste
- [x] Eksisterende tjeneste
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | 5059  |
| **Tjenesteutgavekode**  |  2 |
| **Tjenestetype**  | Innsending  |
| **Volum**  | ca. 4000 (2020)   |
| **Integrasjon**  | Web Service |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [ ] Skal migreres 
- [ ] Skal _IKKE_ migreres

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Er det rollekrav på tjenesten?
- [x] Ja
- [ ] Nei

Kun for organisasjoner.

#### Hvilket sikkerhetsnivå krever tjenesten?
- [ ] Nivå 0
- [ ] Nivå 1
- [ ] Nivå 2
- [ ] Nivå 3
- [ ] Nivå 4

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| FORHM2_SHIP|
| ------------- | ------------- |
|Type Grensesnitt| Web Service |

PDF skal være inkludert i oversendelsen til tjenesteeier.

## Skjermbilder

![image.png](https://images.zenhubusercontent.com/5e676f5c368c082299739eb7/1e3bd2ca-54a5-424d-b681-530b740db13e)

![image](https://user-images.githubusercontent.com/1841665/155503845-74b2a3aa-4a20-426b-a8b9-6172d25bb06b.png)

![image.png](https://images.zenhubusercontent.com/5e676f5c368c082299739eb7/ab1aa44a-c17c-4bc1-a4fa-11a2fed68f18)

## Bruk av Standard Altinn-funksjonalitet
- Sporvalg

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: https://altinn.no/skjemaoversikt/ ....

#### Altinn 2
- Lenke til tjenesten i TUL: https://tul.altinn.no/ ....
- Lenke til tjenesten i Altinn 2.0 (test): https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=5059&Oselect=true
- Lenke til tjenesten i Altinn 2.0 (produksjon): https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=5059&Oselect=true
- XSD: [Arbeidstilsynet_RenholdÅrligMelding_M_2019-04-24_4023_44254_SERES.zip](https://github.com/Altinn/apps-backlog/files/8132283/Arbeidstilsynet_RenholdArligMelding_M_2019-04-24_4023_44254_SERES.zip)

#### Altinn 3
- Lenke til (ny/migrert) tjeneste i Altinn Studio:
- Lenke til (ny/migrert) tjeneste i sluttbrukerløsningen (test):
- Lenke til (ny/migrert) tjeneste i sluttbrukerløsningen (prod):

**Comment by elwal** [comment]
Arbeidstilsynet utvikler skjema selv.
