### ISSUE TITLE
Forhåndsmelding av arbeidsplass hvor det utføres midlertidig eller skiftende bygge- eller anleggsarbeid

### ISSUE THREAD

**Issue by kristoffervp** [Altinn/app-migration#13]
## Innledning

> Byggherren skal sørge for at det sendes en forhåndsmelding til Arbeidstilsynet om bygge- eller anleggsarbeid dersom arbeidet vil vare utover 15 virkedager eller dersom den forventede arbeidsmengde overstiger 250 dagsverk.

#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Ny tjeneste
- [x] Eksisterende tjeneste
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | 2482_  |
| **Tjenesteutgavekode**  |  1 |
| **Tjenestetype**  | Innsending  |
| **Volum**  | 12723 (2019) |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [ ] Skal migreres 
- [ ] Skal _IKKE_ migreres

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Er det rollekrav på tjenesten?
- [ ] Ja
- [x] Nei

Hvis Ja, beskriv rollene og rollekravene nærmere.

#### Hvilket sikkerhetsnivå krever tjenesten?**
- [ ] Nivå 0
- [ ] Nivå 1
- [ ] Nivå 2
- [ ] Nivå 3
- [ ] Nivå 4

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Bruk av Standard Altinn-funksjonalitet
> Fyll ut

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: https://www.altinn.no/skjemaoversikt/arbeidstilsynet/forhandsmelding-av-arbeidsplass-hvor-det-utfores-midlertidig-eller-skiftende-bygge--eller-anleggsarbeid/

#### Altinn 2
- Lenke til tjenesten i TUL: https://tul.altinn.no/ ....
- Lenke til tjenesten i Altinn 2.0 (test): https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=2482&Oselect=true
- Lenke til tjenesten i Altinn 2.0 (produksjon): https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=2482&Oselect=true
- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3
- Lenke til (ny/migrert) tjeneste i Altinn Studio:
- Lenke til (ny/migrert) tjeneste i sluttbrukerløsningen (test):
- Lenke til (ny/migrert) tjeneste i sluttbrukerløsningen (prod):

## Skjembilder

![image](https://user-images.githubusercontent.com/1841665/155517911-afdaad0b-09d2-41e2-8de9-b7009b92a512.png)

**Comment by elwal** [comment]
Arbeidstilsynet utvikler skjema selv.
