### ISSUE TITLE
SIV-1002 Skjema for oppdatering av personopplysninger til Sivilforsvaret 

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-migration#187]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** |   |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

Textresources:
- [x] Check app logo
- [x] Check that it has Alternative text for logo
- [x] Check Appowner
- [x] Check Camelcase on id
- **resource.nb.json:** En del tekst id'er er ikke skrevet med camelCase (men med STORE BOKSTAVER, Storforbokstav)
- Linje 551 og videre (Verdier fra options fil illnesses.json)
- Linje 715 og videre. 

Layout files:
- [x] Camelcase on id
- [x] Use Groups that can be reused in summary and pdf
- [x] If app has an attachment component it should have the same values such as min and max count as in applicationmeta data file.
- [x] Check that it has a pdfReceipt file
- [x] Check Grid and inner grid and make sure it has both xs: and md:
- **03Relative.json**: Linje 166 - Sjekk om det er riktig at grid for xs mangler
- **07VariousPersonnelInformation** - Sjekk om det er riktig at grid ikke skal brukes her
- **08Health** - Sjekk om det er riktig at grid ikke skal brukes her

Applicationmetadata:
- [x] Logo
- [x] check that displayAppOwnerNameInHeader: false
- [x] logo "size" same as the other applications
 
App.csproj:
- [x] Make sure PackageReference version = 7.15.1

Data model:
- [x] Delete minOccurs on required fields.
- **dataModel.xsd + resterende modellfiler**: minOccurs="0" er satt på flere felt som er satt til "required": true i json filene --> Ta bort minOccurs="0" i modellfiler
- [x] Pascal case on name in data model

Options file:
- [x] Make sure all plain text is referred to though text resource id

Logic files:
- [x] Make sure all plain text is referred to though text resource id
- [x] Make sure all custom service implementations is added in Program.cs

Språk:
- [ ] Nynorsk

**Comment by tonygrimstad** [comment]
@andreas-didriksen Resultat av review er lagt inn i sjekklisten over

**Comment by elwal** [comment]
Produksjonssatt 6.06.2024
