### ISSUE TITLE
KRT-1062 Søknad om godkjenning som revisjonsselskap 

### ISSUE THREAD

**Issue by CelineTrammi** [Altinn/app-migration#194]
## Innledning

 
 | Beskrivelse av tjenesten | Søknadsskjema for å godkjennes som revisjonsselskap|
| ------------- | ------------- |
| **Tjenestekode** | 4580 |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending  |
| **Volum**  |   |
| **Integrasjon**  |   |
 

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [ ] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt|  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD:  

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/repos/krt/krt-1062a-1  |
| Altinn 3.0 (test)  | krt.apps.tt02.altinn.no/krt/krt-1062a-1/ |
| Altinn 3.0 (prod)  | .... |

**Comment by CelineTrammi** [comment]
Fikset tilbakemeldinger fra fag

**Comment by elwal** [comment]
Skjema produksjonssatt 8.12.2023
