### ISSUE TITLE
SIV-1015 Bekreftelse på mottatt pålegg om tjenesteplikt

### ISSUE THREAD

**Issue by NathalieFroissart** [Altinn/app-migration#195]
## Innledning

 
 | Beskrivelse av tjenesten | Ensidigt skjema hvor brukere enten bekrefter eller sender in en klagan på mottatt pålegg om tjensteplikt|
| ------------- | ------------- |
| **Tjenestekode** |   |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending  |
| **Volum**  |   |
| **Integrasjon**  |   |
 

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt|  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

Altinn2

![Image](https://github.com/Altinn/app-migration/assets/39302088/43852e85-1bd8-43ca-b381-381bcf43d16c)

Altinn 3 

![Image](https://github.com/Altinn/app-migration/assets/39302088/667bdd67-78cd-4d25-a0d4-8779b5dfaf05)

![Image](https://github.com/Altinn/app-migration/assets/39302088/f63b012c-731e-41d6-8378-399b6edd95ff)

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD:  

TASK:
- [x] Logo
- [x] Påkrevde felt, fjerne minOccurs="0" i datamodellen
- [x] Design godkjent (DSB)
- [x] Kode Review (Per)
- [x] fjern saksbehandlande distrikt
- [x] fix groups in summary og pdf
- [ ] test(DSB) 
- [x] nynorsk  

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/repos/dsb/siv-1015-kvittering-tjplikt  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by PerAndresen** [comment]
Code Review: Well done. Good looking schema, with good dynamic frontend functionality. No uneccesary code and good variable names.

**Comment by PerAndresen** [comment]
Flytter denne til test @RadhaRajagopalan @NathalieFroissart

**Comment by elwal** [comment]
Produksjonssatt 17.01.24
