### ISSUE TITLE
Innsendingstjeneste for Statens havarikommisjon

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#20]
#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Ny tjeneste
- [X] Eksisterende tjeneste
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | _5292_  |
| **Tjenesteutgavekode**  |  _1_ |
| **Tjenestetype**  | _Innsending_  |
| **Volum**  | _20_  |
| **Integrasjon**  | _DownloadQueue_ |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [X] Skal migreres 
- [ ] Skal _IKKE_ migreres
- [ ] Vet ikke

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Er det rollekrav på tjenesten?
- [X] Ja
- [ ] Nei

Utfyller/innsender

#### Hvilket sikkerhetsnivå krever tjenesten?
- [ ] Nivå 0
- [ ] Nivå 1
- [X] Nivå 2
- [ ] Nivå 3
- [ ] Nivå 4

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [X] Nei

_Sendes inn ved behov._

### Integrasjon

 _DownloadQueue_  

## Skjermbilder

Skjema består av èn side. Siden er ulik basert på om du rapporterer som privatperson eller organisasjon.

Som organisasjon:

![image](https://user-images.githubusercontent.com/29474941/156144571-8bc2a531-b436-4f2e-9534-3d827ab6a2cc.png)

Som privatperson:

![image](https://user-images.githubusercontent.com/29474941/156144711-e9149c69-21d6-426a-8c31-ffffda2f2355.png)

De har også laget en egen utgave for engelsk versjon på sikkerhetsnivå 0 for egenregistrerte brukere (utenlandske brukere) (https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=5292&Oselect=true)

![image](https://user-images.githubusercontent.com/29474941/156145119-123fc398-6cf7-4dbc-8401-f4bc7ff20ae9.png)

## Bruk av Standard Altinn-funksjonalitet
Engelsk utgave på sikkerhetsnivå 0

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/statens-havarikommisjon/nnsendingstjeneste-for-statens-havarikommisjon-for-transport/ |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/sht/Havari-01/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5292&Oselect=true |
| Altinn 2.0 (prod)  | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5292&Oselect=true  |

- XSD: 
[Kursdomene_DemoSHT_M_2019-03-08_5480_34163_SERES.zip](https://github.com/Altinn/apps-backlog/files/8160656/Kursdomene_DemoSHT_M_2019-03-08_5480_34163_SERES.zip)

- Skjemapakke:
[TULPACKAGEb40f9fa0-4024-4809-b3af-80564e641a5d.zip](https://github.com/Altinn/apps-backlog/files/8168431/TULPACKAGEb40f9fa0-4024-4809-b3af-80564e641a5d.zip)

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.studio/repos/ttd/innsendingstjeneste-shk |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by andreas-didriksen** [comment]
https://altinn.studio/repos/ttd/innsendingstjeneste-shk

**Comment by elwal** [comment]
Tjenesten skal ikke over til Altinn 3.
