### ISSUE TITLE
KRT-1064 Søknad om autorisasjon som tilbyder av virksomhetstjenester

### ISSUE THREAD

**Issue by CelineTrammi** [Altinn/app-migration#202]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | 4985  |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending  |
| **Volum**  |  |
| **Integrasjon**  |  |
 

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Nåværende progresjon i skjema
🥅➖⚽️➖➖➖➖➖➖➖🏃‍♂️
## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=3&ServiceCode=4985  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/repos/krt/krt-1064a-1  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Prodsatt 19.04.2024
