### ISSUE TITLE
SIV-1001 Reiseregning

### ISSUE THREAD

**Issue by walldenfilippa** [Altinn/app-migration#207]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** |   |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.
![image](https://github.com/Altinn/app-migration/assets/143729834/d5c6451e-bef0-470b-93c8-ef3beb5091aa)
![image](https://github.com/Altinn/app-migration/assets/143729834/57e4cc8f-3e9f-4207-b59a-b951d324a7ef)
![image](https://github.com/Altinn/app-migration/assets/143729834/be99867f-c081-42f7-aeed-5b46a3b818d9)

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/repos/dsb/siv-1001-reiseregning |
| Altinn 3.0 (test)  | [dsb.apps.tt02.altinn.no/dsb/siv-1001-reiseregning/](https://dsb.apps.tt02.altinn.no/dsb/siv-1001-reiseregning/) |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 6.06.2024.
