### ISSUE TITLE
SIV-1004 Søknad om næringsbidrag

### ISSUE THREAD

**Issue by walldenfilippa** [Altinn/app-migration#208]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** |   |
| **Tjenesteutgavekode**  |  |
| **Tjenestetype**  | Innsending  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.
![image](https://github.com/Altinn/app-migration/assets/143729834/a8ba1bf9-31bb-4748-9233-e72a0af78009)
![image](https://github.com/Altinn/app-migration/assets/143729834/39b09ce4-8fc5-4f8b-973e-a90986d49fe4)
![image](https://github.com/Altinn/app-migration/assets/143729834/514c3195-9802-41d1-af91-0a905436a3c4)
![image](https://github.com/Altinn/app-migration/assets/143729834/2b9cc44a-bcfa-4362-876d-0f52c0eab0a0)

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  |   |
| Altinn 2.0 (prod)  |  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  https://altinn.studio/repos/dsb/siv-1004-naeringsbidrag  |
| Altinn 3.0 (test)  |  https://dsb.apps.tt02.altinn.no/dsb/siv-1004-naeringsbidrag/  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 12.03.24
