### ISSUE TITLE
SIV-1009 Forespørsel vedrørende manglende fremmøte

### ISSUE THREAD

**Issue by tonygrimstad** [Altinn/app-migration#216]
## Innledning

 
| Beskrivelse av tjenesten | _Skjemaet sendes ut sammen med brev med forespørsel om manglende fremmøte på rekrutteringsmøte/kurs/øvelse/innsats dersom den innkalte (ansatt/søker) ikke har deltatt på innkalt aktivitet eller søkt fritak fra denne_ |
| ------------- | ------------- |
| **Tjenestekode** | 5127  |
| **Tjenesteutgavekode**  | 1|
| **Tjenestetype**  | __Innsending__/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
__Kun portal-innsending__
Kun sluttbrukersystem-innsending
Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
Ja
__Nei__

#### Har tjenesten frister eller andre egenskaper?
Ja
__Nei__

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  |  |
| TUL  | http://tul.altinn.cloud/sites/dsb/SIV-1009/Utgave1/default.aspx  |
| Altinn 2.0  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5127 |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  |  ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Duplikat av #213
