### ISSUE TITLE
KRT-1186 Søknad om å drive forsikringsformidling

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#223]
## Innledning

 
 | Beskrivelse av tjenesten | _Dette skjemaet skal benyttes ved søknad om tillatelse til å drive forsikringsmegling eller gjenforsikringsmegling, og ved søknad om registrering som forsikringsagentforetak eller aksessorisk forsikringsagentforetak_ |
| ------------- | ------------- |
| **Tjenestekode** | 5769  |
| **Tjenesteutgavekode**  | 2 |
| **Tjenestetype**  | Innsending |

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [X] Nei

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/finanstilsynet/soknad-om-registrering-som-forsikringsagentvirksomhet-eller-tillatelse-som-forsikringsmeglingsforetak/ |
| TUL  | http://tul.altinn.cloud/sites/krt/KRT-1186/Utgave2/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=5769 |

**Comment by CelineTrammi** [comment]
KRT utviklere jobber med denne
