### ISSUE TITLE
KRT-1187 Forsikringsforetakets bekreftelse ved avtale om formidling av forsikringer

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#224]
## Innledning

 
 | Beskrivelse av tjenesten | _Forsikringsforetak skal ved inngåelse av forsikringsformidlingsavtale påse at vilkårene for registrering i forsikringsformidlingsloven er oppfylt hos det foretaket de inngår avtale med_ |
| ------------- | ------------- |
| **Tjenestekode** | 5777  |
| **Tjenesteutgavekode**  | 2 |
| **Tjenestetype**  | Innsending  |

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [X] Nei

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/finanstilsynet/Forsikringsforetakets-bekreftelse-ved-avtale-om-formidling-av-forsikringer/ |
| TUL  | http://tul.altinn.cloud/sites/krt/KRT-1187/Utgave2/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=5777  |

**Comment by CelineTrammi** [comment]
KRT utviklere jobber med denne
