### ISSUE TITLE
KRT-1227 Melding om livsforsikringsprodukt og pristariff

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#225]
## Innledning

 
 | Beskrivelse av tjenesten | _Forsikrings- og pensjonskasser skal gi melding til Finanstilsynet om livsforsikringsprodukter som foretaket tilbyr, og om pristariffer og prinsippene for utforming av disse. Meldeplikten gjelder også innskuddspensjonsforetak, forvaltningsselskap for verdipapirfond og banker som tilbyr pensjonssparing etter lov om innskuddspensjon i arbeidsforhold_ |
| ------------- | ------------- |
| **Tjenestekode** | 5650  |
| **Tjenesteutgavekode**  | 1 |
| **Tjenestetype**  | Innsending  |

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [X] Nei

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/finanstilsynet/melding-om-livsforsikringsprodukt-og-pristariff/ |
| TUL  | http://tul.altinn.cloud/sites/krt/KRT-1227/Utgave1/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5650 |

**Comment by CelineTrammi** [comment]
Joakim hos Finanstilsynet tar denne
