### ISSUE TITLE
Miljøvernutgifter for mottaks- og prosesseringsanlegg på land (RA-0672)

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#25]
#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Ny tjeneste
- [x] Eksisterende tjeneste **(Gjelder 3 rimelig like tjenester: RA-0672, RA-0673 og RA-0514)**
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | RA-0672 Miljøvernutgifter for mottaks- og prosesseringsanlegg på land , gjelder også RA-0673 og RA-0514|
| ------------- | ------------- |
| **Tjenestekode** | 4494  |
| **Tjenesteutgavekode**  | 2 |
| **Tjenestetype**  | Innsending  |
| **Volum**  | ca 10 pr år  |
| **Integrasjon**  |  SFTP  |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [x] Skal migreres 
- [ ] Skal _IKKE_ migreres
- [ ] Vet ikke

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Er det rollekrav på tjenesten?
- [x] Ja
- [ ] Nei

![image](https://user-images.githubusercontent.com/43333852/159000743-1bcca7be-29c1-478e-9a4b-78122ef1e034.png)

#### Hvilket sikkerhetsnivå krever tjenesten?
- [ ] Nivå 0
- [ ] Nivå 1
- [x] Nivå 2
- [ ] Nivå 3
- [ ] Nivå 4

#### Har tjenesten frister eller andre egenskaper?
- [x] Ja, årlig innsending, frist satt vha. prefill
- [ ] Nei

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| SFTP  |

## Behov for funksjonalitet
- [ ] https://github.com/Altinn/app-frontend-react/issues/138
- [ ] https://github.com/Altinn/app-frontend-react/issues/297
- [ ] Enklere metode for å angi valideringer enn med dagens bruk av C# backend

**Sperrende issues:**

- [ ] https://github.com/Altinn/app-frontend-react/issues/243
- [ ] https://github.com/Altinn/app-frontend-react/issues/68
- [ ] https://github.com/Altinn/app-frontend-react/issues/190

## Skjermbilder

**Punktene nedenfor er behov SSB har, for skjemaene RA-0672, RA-0673 og RA-0514, som mangler Altinn3-funksjonalitet.**

- Behov for tekst som utheves som viktig informasjon," informasjonsboks". Dette er brukt flere steder i dette skjemaet. 
 ![image](https://user-images.githubusercontent.com/43333852/159003386-dce09b16-61c1-479a-b024-d5b2ea053b17.png)

- Oppstilling av enkeltfelter i "matriseform" må vi finne en alternativ løsning for da dette ikke kan løses i Altinn 3 vha "grid".  Ved bruk av "grid" vil "skjermlesere" se dette som enkeltfelter, enkeltfelter uten overskrift (title) tilfredstiller ikke UU. Problemet er diskutert i denne tråden, uten konkret løsning: https://altinn.slack.com/archives/C02EVE4RU82/p1646749340197709?thread_ts=1645612313.032579&cid=C02EVE4RU82
Her er også plassering av ?-hjelpetekst et spørsmål om vi får til: 
![image](https://user-images.githubusercontent.com/43333852/159004641-2278ebdb-61ca-43b4-bab1-e047e0052aea.png)
![image](https://user-images.githubusercontent.com/43333852/159007875-29d86959-4ca8-467d-9250-2f66177a02a1.png)
![image](https://user-images.githubusercontent.com/43333852/159005021-69821495-3b62-467d-9255-33497eaae5a1.png)
![image](https://user-images.githubusercontent.com/43333852/159008014-77331941-a36a-408d-8996-a0187f869128.png)

- De fleste av feltene i disse skjemaene har valideringer på tvers av feltene, dagens metode for å gjøre slike valideringer i C# medfører mye kode og store utviklingskostnader. Ikke minst store vedlikeholdskostnader. For å realisere alle krav som stilles av kontroller i disse skjemaene (ref. [RuleInspector.pdf](https://github.com/Altinn/apps-backlog/files/8304809/RuleInspector.pdf))  må man ha på plass en enklere metode for å sette opp valideringer.

## Bruk av Standard Altinn-funksjonalitet
- Ingen spesialkode
- Veldig mange kontroller, noen myke: 
[RuleInspector.pdf](https://github.com/Altinn/apps-backlog/files/8304809/RuleInspector.pdf)

- Noe forholdsmessig enkel dynamikk på sidene

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: 
 

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/statistisk-sentralbyra/miljovernutgifter-for-mottaks--og-prosesseringsanlegg-pa-land-/ |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/ssb/RA-0672/Utgave2/default.aspx |
| Kildefiler på TUL-Share  | \\ai-tul.osl.basefarm.net\TUL\TULShare\InfoPath\Etater\SSB\PROD\RA-0672 Miljøvernutgifter for mottaks- og prosesseringsanlegg på land\Utgave 2 |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=4494 |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

Instansieringskontroll slått av KUN i TT02, PROD krever abo.

- XSD: Datamodell skal bygges på nytt for å få den mer A3-vennlig

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by StianVestli** [comment]
Disse gjelder også RA-0815 og RA-0678:

- https://github.com/Altinn/altinn-studio/issues/8334
- https://github.com/Altinn/altinn-studio/issues/8275

**Comment by rvessb** [comment]
Ang punktet om "Oppstilling av enkeltfelter i matriseform". Man kunne ha tenkt seg å teste ut hvordan det ville fungert å bruke komponenten repeterende gruppe for å dekke matrise-behovet i dette skjemaet, men det vil i så fall betinge at meldte behov på denne komponenten løses.  (app-frontend-react issue #61, #62, #64 )

**Comment by rvessb** [comment]
@elwal Det har gått meg hus forbi at det **fremdeles** ikke er støtte for å vise tjenesteeiers logo i header på skjemaet, dette bør prioriteres da det gjelder alle våre tjenester. Se tråd i slack https://altinn.slack.com/archives/C02ESDSTVGD/p1646740757232499

Behovet er altså meldt i https://github.com/Altinn/altinn-studio/issues/1614 og https://github.com/Altinn/altinn-cdn/issues/89

**Comment by elwal** [comment]
@rvessb har lagt inn #1614 som blokker og følger opp ift prioritering.

**Comment by rvessb** [comment]
> Ang punktet om "Oppstilling av enkeltfelter i matriseform". Man kunne ha tenkt seg å teste ut hvordan det ville fungert å bruke komponenten repeterende gruppe for å dekke matrise-behovet i dette skjemaet, men det vil i så fall betinge at meldte behov på denne komponenten løses. (app-frontend-react issue ([Altinn/app-frontend-react#61](https://github.com/Altinn/app-frontend-react/issues/61)), ([Altinn/app-frontend-react#62](https://github.com/Altinn/app-frontend-react/issues/62)), ([Altinn/app-frontend-react#64](https://github.com/Altinn/app-frontend-react/issues/64)), [Altinn/app-frontend-react#68](https://github.com/Altinn/app-frontend-react/issues/68))

@elwal Etter å ha testet litt "repeterende gruppe" for dette skjemaet ser vi at det fremdeles mangler funksjon for å åpne gruppen inni selve tabellen, nå åpnes alle gruppene i bunnen av tabellen (When editing a row, the row should expand, and the group should open inside the table, like showed in the sketches.). Mener det ble sagt at dette ble jobbet med, men finner ingen egen sak på det i https://github.com/Altinn/app-frontend-react/issues/60? Denne funksjonaliteten er blokkerende DERSOM vi skal løse dette skjemaet vha "repeterende gruppe".

https://github.com/Altinn/app-frontend-react/issues/190 er også blokkerende for repeterende gruppe.

Dersom vi blir enige om å satse på repeterende gruppe kan https://github.com/altinn/altinn-studio/issues/4357 fjernes som blokkerende for denne saken.

**Comment by elwal** [comment]
Produksjonssatt 31.01.23
