### ISSUE TITLE
Endring av rolle samt oppdatering av navn på "Søknad om data fra NPR, KPR og IPLOS-registeret"

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#251]
## Innledning

Applikasjonen "Søknad om data fra NPR, KPR og IPLOS-registeret" ligger inne med feil rolle. Tjenesten skal kun ha rollen "Helse-, sosial- og velferdstjenester (UIHTL)".

Repo til app: https://altinn.studio/repos/fhi/npr-kpr-iplos

I tillegg må det legges inn fullt navn på appen i applicationmetadata-filen:

Bokmål: Søknad om data fra NPR, KPR og IPLOS-registeret
Nynorsk: Søknad om data frå NPR, KPR og IPLOS-registeret

**Comment by andreas-didriksen** [comment]
Løst.
