### ISSUE TITLE
Endring av varslingsadresse på mottaks-appen til "Søknad om data fra NPR, KPR og IPLOS-registeret

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#252]
## Innledning

FHI ønsker å endre adressen fra

folkehelseinstituttet@fhi.no

til

kundehenvendelser.postmottak@nhn.no

Mottaks-app: https://altinn.studio/repos/fhi/mottak-skjema

**Comment by andreas-didriksen** [comment]
@elwal da skal denne være løst. FHI kan nå teste at dette fungerer i produksjon.
