### ISSUE TITLE
Konfigurere eFormidling integrasjon for appen "Skjema for tilskudd til økt digital deltakelse og kompetanse" 

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#262]
## Innledning

 
App: https://altinn.studio/repos/digdir/tilskudd-dig-delt-komp

**Oppgaver:**
- [x] Konfigurere appen for eFormidling
- [ ] Forbedre og oppdatere [dokumentasjonen](https://docs.altinn.studio//nb/app/development/configuration/eformidling/) Altinn/altinn-studio-docs/pull/1704
 
Appen skal produksjonssettes i slutten av mars.

**Noen ønsker for dokumentasjonen:**

- en ryddig og god sjekkliste for hele prosessen
- flere/bedre kodeeksempler
- få frem i dokumentasjonen at man ønsker et en-til-en forhold mellom klient i maskinporten og app

**Comment by NathalieFroissart** [comment]
NB: Filippa reviewer
