### ISSUE TITLE
Endringer i skjema for samhandlingsavvik

### ISSUE THREAD

**Issue by thomahan** [Altinn/app-migration#275]
Info fra HMR:

Vi ser at det er behov for å endre litt på skjemaet for samhandlingsavvik: https://altinn.studio/repos/hmrhf/newsamhandlingsavvik

1.	
Det er ønskelig å endre på tilgangsoppsettet til skjemaet for samhandlingsavvik slik at det blir tilsvarende til skjemaet for "Melding om feil i HP" (https://altinn.studio/repos/hmrhf/bekymringsmelding-hpf): Nærmere beskrevet er det ønskelig at man skal kunne logge inn som privat person, og/eller få tilgang på skjemaet ved å ha rollen utfyller/innsender i en organisasjon eller få tildelt skjemaet. Årsaken til de ønskede endringene er at vi vil at skjemaet for samhandlingsavvik skal være like tilgjengelig som skjemaet for "Melding om feil HP" - nå ser vi at fastlegene bruker skjemaet for melding om feil i HP og jeg mistenker at tilgangen til skjema for samhandlingsavvik har vært medvirkende til at det i liten grad brukes av fastleger.

2.	
Det er ønskelig å endre informasjon om avsender i skjema for samhandlingsavvik slik at det blir likt med oppsettet i skjema for "Melding om feil i HP". 
Kan du dele opp slik at innsender må velge enten kommune eller legekontor. Dersom en velger kommune så får man ikke opp legekontor og motsatt. Dersom man velger kommune, så kan nedtrekksliste over kommuner i Møre og Romsdal komme opp med automatisk oppslag på organisasjonsnummer. Der må i tillegg være et felt for Virksomhet/enhet. Dersom innsender velger legekontor, så må navn på legekontor fylles ut i et manuelt felt. Her har vi ikke en oversikt over organisasjonsnummer, så det må lages et felt for organisasjonsnummer som legekontoret fyller ut manuelt.

**Comment by elwal** [comment]
Skjema er testet og ble prodsatt 8.08.24.
