### ISSUE TITLE
KRT-1186 fikse en feil i produksjonen

### ISSUE THREAD

**Issue by Ahmed-Ghanam** [Altinn/app-migration#300]
Brukere opplever utfordringer med skjemaet krt-1186. Dette skyldes en feil i funksjonen ValidateOrgNr, som benytter en feilaktig indeks for å hente data fra en samling. Dette kan fikses ved å korrigere koden og publisere skjemaet på nytt.

**Comment by elwal** [comment]
Kodeendring utført.
