### ISSUE TITLE
Sende dokumenter til Helse Møre og Romsdal (PDF til HMRHF)

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/app-migration#41]
#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Ny tjeneste
- [x] Eksisterende tjeneste
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | _5587_  |
| **Tjenesteutgavekode**  |  _5587_ |
| **Tjenestetype**  | Innsending |
| **Volum**  | _Ukjent pga. typen grensesnitt som brukes i 2.0_  |
| **Integrasjon**  | _Sendes til innboks_ |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [x] Skal migreres 
- [ ] Skal _IKKE_ migreres
- [ ] Vet ikke

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

### Integrasjon

| Grensesnitt| _Detaljer_ |
| ------------- | ------------- |
|A2: Melding til innboks| _Sender melding til HMRHF sin innboks i Altinn ved nye skjema_  |
|A3: ?| _Sikri har laget integrasjon mot Elements for GK, kan HMRHF bruke samme integrasjon?_  |

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: 

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | ....  |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/hmrhf/PDFtilHMR/PDFtilHMR/default.aspx |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=5587&ServiceCode=5587 |
| Altinn 2.0 (prod)  | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=5587&ServiceCode=5587 |

- XSD: _Last opp XSD her (i .zip-format)_
https://altinn.studio/repos/hmrhf/hmrhf-datamodels
#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | .... |
| Altinn 3.0 (test)  | .... |
| Altinn 3.0 (prod)  | .... |

## Skjermbilder
![image](https://user-images.githubusercontent.com/45939254/167120989-c950df93-4f21-4924-8cdc-dd60a07c138a.png)

**Comment by andreas-didriksen** [comment]
Legger denne tilbake fordi den Altinn 2 skjema fortsatt er i produksjon.
Den nye Altinn 3 appen er publisert i prod, men usikker på om det er satt opp noe mottak for A3 appen.

**Comment by elwal** [comment]
Appen er produksjonssatt men mangler mottak. De ønsker at skjema skal gå i innboksen deres i Altinn. Opprettet eget issue på det.
