### ISSUE TITLE
Skjema for registrering av samhandlingsavvik

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/app-migration#42]
#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Ny tjeneste
- [x] Eksisterende tjeneste
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | _5555_  |
| **Tjenesteutgavekode**  |  _12020_ |
| **Tjenestetype**  | Innsending |
| **Volum**  | _Ukjent pga. typen grensesnitt som brukes i 2.0_  |
| **Integrasjon**  | _Sendes til innboks_ |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [x] Skal migreres 
- [ ] Skal _IKKE_ migreres
- [ ] Vet ikke

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

### Integrasjon

| Grensesnitt| _Detaljer_ |
| ------------- | ------------- |
|A2: Melding til innboks| _Sender melding til HMRHF sin innboks i Altinn ved nye skjema_  |
|A3: ?| _Sikri har laget integrasjon mot Elements for GK, kan HMRHF bruke samme integrasjon?_  |

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: 

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen      | ....  |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/hmrhf/Samhandlingsavvik/Samhandlingsavvik/default.aspx |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=12020&ServiceCode=5555 |
| Altinn 2.0 (test nivå_3)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=7777&ServiceCode=5555 |
| Altinn 2.0 (prod)  | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=12020&ServiceCode=5555 |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | .... |
| Altinn 3.0 (test)  | .... |
| Altinn 3.0 (prod)  | .... |

## Skjermbilder
![image](https://user-images.githubusercontent.com/45939254/173824614-f89fbaa8-5d9d-4176-9564-64715844529e.png)

**Comment by AinaEngen** [comment]
@tommyalmendingen - hva er status på denne?

**Comment by elwal** [comment]
Produksjonssatt 31.01.23
