### ISSUE TITLE
Perioderapportskjema godsoverføring

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-migration#44]
#### Er tjenesten en ny eller eksisterende tjeneste?
- [ ] Eksisterende tjeneste
 
 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | _4904_  |
| **Tjenesteutgavekode**  |  _Legg inn tjenesteutgavekode (ServiceEditionCode)_ |
| **Tjenestetype**  | Innsending |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [ ] Skal migreres 
- [ ] Skal _IKKE_ migreres
- [x] Vet ikke

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [ ] Nei

#### Er det rollekrav på tjenesten?
- [ ] Ja

Hvis Ja, beskriv rollene og rollekravene nærmere.
 Utfyller/innsender. 

#### Hvilket sikkerhetsnivå krever tjenesten?
- [ ] Nivå 2

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.
![image.png](https://images.zenhubusercontent.com/60213a7e6a13c61f6bd6ba8b/508feecc-53f8-49ee-86eb-814e7a621f71)
![image.png](https://images.zenhubusercontent.com/60213a7e6a13c61f6bd6ba8b/f8760b7e-f6f0-45f1-9ed6-0cdf1e97a59b)
## Bruk av Standard Altinn-funksjonalitet
> Fyll ut

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: https://www.altinn.no/skjemaoversikt/kystverket/perioderapportskjema-godsoverforing/

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ https://altinn.studio/repos/ttd/perioderapport-godsoverforing |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by andreas-didriksen** [comment]
https://altinn.studio/repos/ttd/perioderapport-godsoverforing

**Comment by elwal** [comment]
Duplikat av #226
