### ISSUE TITLE
MT0002 mistenkelige transaksjoner

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-migration#5]
## Description

This issue will cover the process to migrate MT0002 from Altinn 2 to Altinn 3

## Screenshots current Altinn 2 service 

![image](https://user-images.githubusercontent.com/13309071/142178262-5531b82f-f2e0-46d1-bfde-1600eadcbf4f.png)

![image](https://user-images.githubusercontent.com/13309071/142178673-c67984d8-1cb9-47c8-8efa-a46541bfa1b0.png)

![image](https://user-images.githubusercontent.com/13309071/142179114-57f961e1-b40d-4a46-a950-3f904431d4d7.png)

![image](https://user-images.githubusercontent.com/13309071/142179429-08f0b454-2aed-4515-ba8a-0fb551f61fa5.png)

###  Pure re-implementation or re-imagine the service?

We need to decide if we just will move the form to Altinn 3 with a design that is based on Altinn 2 or are we gonna try reimagne the application, simplify, improve experience ++  .  Also see [guidelines](https://docs.altinn.studio/app/design/insight/)

- [ ] Decide scope for reimplementation

### Datamodel - resuse or new?

What are the requirements for the data model? Should it be the exact same XSD used? 

### End user system integration

In Altinn 3 the end-user system concept is removed and we currently only support ID-porten usage.

Is this an acceptable solution? 

Maskinporten is currently not supported for end users. 

### Org integration

Altinn 3 requires orgs to download the data from the APIS. In Altinn 2 data is pushed. 

Police would need to set up a webhook to receive events or poll Altinn API for events regarding submitted forms

Have police identified needs to change on their side?

Do they have some limitations? 

Timeline?

Is there missing functionality in Altinn 3 side that would help?

### Form components needed

The current form seems like standard components but there are drop-down lists that use data from groups in data. 

This is currently not supported
Related to 

Altinn/altinn-studio#5247
Altinn/altinn-studio#7626

### Auto delete

We assume that the form should not be available from archive?

### Attachments

Should attachments be allowed

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Create FIGMA prototype
- [ ] Usertest?
- [ ] IDentity missing components/functionality in Altinn 3
- [ ] Create issues in Altinn 3 backlog for missing functionality. 

## Development tasks
> Add tasks here

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by elwal** [comment]
Økokrim ønsker ikke å ta i bruk Altinn 3 pga schrems.
