### ISSUE TITLE
Begjæring om gjenåpning

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/app-migration#53]
## Innledning

| **Beskrivelse av tjenesten**      | _Skjema som brukes for å søke om gjenåpning av straffesaker_ |
| ----------------------------- | --------------------------- |
| **Volum**                     | _ca. 200_  |
| **Planlagt produksjonssatt**  | _dd.mm.22_                  |

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året, hendelsesbasert._

## Behov for funksjonalitet
> Fyll ut

## Lenker og filer

| Område            | Lenke     |
| ----------------- | --------- |
| Altinn Studio     | https://altinn.studio/designer/gk/gjenopptakelse#/about |
| Altinn 3.0 (test) | https://gk.apps.tt02.altinn.no/gk/gjenopptakelse/ |

**Comment by AinaEngen** [comment]
@tommyalmendingen - hva er status på denne?
