### ISSUE TITLE
Vareundersøkelse for industrien (RA-1130)

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#55]
## Innledning

 
 | Beskrivelse av tjenesten | _SSB trenger opplysninger om vareproduksjon i industrien for å få et godt beregningsgrunnlag til nasjonalregnskapet._ |
| ------------- | ------------- |
| **Tjenestekode** | _4312_  |
| **Tjenesteutgavekode**  |  _2_ |
| **Tjenestetype**  | _Innsending_  |
| **Volum**  | _2200 (tall fra 2021)_  |
 

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [X] Nei

#### Har tjenesten frister eller andre egenskaper?
- [X] Ja
- [ ] Nei

_Årlig. Frist settes vha prefill._

## Behov for funksjonalitet
- [ ] https://github.com/Altinn/app-frontend-react/issues/62
- [ ] https://github.com/Altinn/app-frontend-react/issues/243
- [ ] https://github.com/Altinn/app-frontend-react/issues/68
- [ ] https://github.com/Altinn/app-frontend-react/issues/190
- [ ] https://github.com/Altinn/app-frontend-react/issues/61
- [ ] https://github.com/Altinn/app-frontend-react/issues/64
- [ ] https://github.com/Altinn/app-frontend-react/issues/477
- [ ] https://github.com/Altinn/app-frontend-react/issues/614
- [ ] https://github.com/Altinn/app-frontend-react/issues/295
- [ ] https://github.com/Altinn/app-frontend-react/issues/586
- [ ] https://github.com/Altinn/app-frontend-react/issues/504
- [ ] https://github.com/Altinn/app-frontend-react/issues/883
- [ ] https://github.com/Altinn/altinn-studio/issues/8279

Summeringstabell under tabellen og mulighet til å legge til engne varer:
![image](https://user-images.githubusercontent.com/43333852/191031583-2b33e84e-0a6e-44ed-a066-cc154d060b30.png)

Felter skrivebeskyttet på preutfylte rader:
![image](https://user-images.githubusercontent.com/43333852/191031804-8ebf8666-595a-4e76-8631-c6c3d6a50f69.png)

Ny vare lagt til av rapportør. felter er ikke skrivebeskyttet:
![image](https://user-images.githubusercontent.com/43333852/191032005-695732fc-1261-4300-9a0a-70efdfb11b3b.png)

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/statistisk-sentralbyra/vareundersokelse-for-industrien/  |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/ssb/RA-1130/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=4312 |

**Comment by rvessb** [comment]
@elwal https://github.com/Altinn/app-frontend-react/issues/295 lagt til som behov og skal opp på sperrende

**Comment by elwal** [comment]
Tjeneste produksjonssatt 22.05.23.
