### ISSUE TITLE
Jakt- og fangstrapporteringen (RA-0574)

### ISSUE THREAD

**Issue by elwal** [Altinn/app-migration#59]
## Innledning

 
 | Beskrivelse av tjenesten | _Formålet med undersøkelsen er å lage offisiell statistikk om utbyttet fra småvilt-, villsvin- og rådyrjakt. I tillegg skal undersøkelsen kartlegge hvor mange jegere som har deltatt i jakt på viltartene som det er åpnet for jakt på._ |
| ------------- | ------------- |
| **Tjenestekode** | _4927_  |
| **Tjenesteutgavekode**  |  _1_ |
| **Tjenestetype**  | _Innsending_  |
| **Volum**  | _213257 (tall fra 2021)_  |
 

#### Hvordan benyttes Tjenesten?
- [X] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten frister eller andre egenskaper?
- [X] Ja
- [ ] Nei

_Årlig. Frist for innsending er 1. mai._

## Behov for funksjonalitet
- [ ] https://github.com/Altinn/app-frontend-react/issues/396
- [ ] https://github.com/Altinn/app-frontend-react/issues/395
- [ ] https://github.com/Altinn/altinn-studio/issues/3717
- [ ] https://github.com/Altinn/app-frontend-react/issues/726
- [ ] https://github.com/Altinn/app-frontend-react/issues/504
- [ ] https://github.com/Altinn/app-frontend-react/issues/883
- [ ] https://github.com/Altinn/altinn-studio/issues/8279
- [ ] https://github.com/Altinn/app-frontend-react/issues/1098
- [ ] https://github.com/Altinn/app-frontend-react/issues/1111
#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/statistisk-sentralbyra/jaktundersokelsen/ |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/ssb/RA-0574/RA-0574/default.aspx |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=4927 |
| Altinn 2.0 (prod)  | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=4927&Oselect=true  |

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by rvessb** [comment]
@elwal kan du sette disse to som sperrende på denne tjenesten: 
https://github.com/Altinn/app-frontend-react/issues/1098
https://github.com/Altinn/app-frontend-react/issues/1111

Du kan fjerne "repeating fields" som sperrende, vi har fått en del nye muligheter som vi har benyttet oss av som gjør at vi ikke er avhengig av den komponenten på dette skjemaet.

**Comment by elwal** [comment]
Prodsatt 9.11.2023
