### ISSUE TITLE
Oppstartsveileder enkeltpersonforetak

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-migration#6]
## Description
This issue should document what we need to develop to support this application. This is a draft and the issues needs to be verified and prioritized. 

- [ ] Describe the application here...
- [ ] Insert screenshots of the application
- [ ] Create remaining issues
- [ ] Is this issue enough to give a good overview of the issues needed to create this application?
- [ ] validate with a developer that we have all issues covered here 

(Not in a prioritized order)

## Styling
In this section I will collect all missing issues that relates to how the application looks. This app will present the user with a lot of information and the possibilites to structure this in a good way will be very important.

**Labels as headers**
This application will have many pages with only one input per page. With todays styling the label gets very small when only having one input. To give a better focused view we should let the developer style the label as a header.  Altinn/app-frontend-react#189 

**Info panel**
With a lot of texts and information, some needs to be highlighted. Panels might be a way to support this Altinn/altinn-studio#6068
This is also relevant to feedback on the calculation page or other places where we might want to give direct feedback 

**Read-only fields** 
The calculator will show an important value to the user. These fields should not be styled the same as deactivated fields.
Altinn/app-frontend-react#29

**Vertical radiobuttons** (Fixed)
The horizontal view of the radiobuttons are a bit too close. We should enhance the readability by adding vertical view for two radiobuttons. Altinn/altinn-studio#5730

**Extra space above header**
In the calculator page we need more space between the sections. This should be handled in the header component. 
Altinn/app-frontend-react#156 

## Functionality
There are parts of this application functionality that we either lack or is not discussed enough how we are going to solve. 

**The user should be able to change input from earlier in the form from the recommendation page(The last page)**
We might be able to use the "check answer component here", but it would have to look different then today. 

**Print**
Our pdf generator will not be able to support what the user needs in this app. One solution is to create a print view for the last page so that the user can print the recommendation if they want.

**No data is sent**
The user will get a recommendation based on their input. All the calculation is done by the app therefor the data does not need to be sent anywhere. 
- Should the user be able to "submit" an app like this or should it be open until the user deletes it from their inbox?
- Are there anything we need to fix on our end to support this? 

**The user should be able to find correct næringskode and select it**
The quickest solution for this is to only support a drop down menu, but this will be a cumbersome solution if this list contains a lot of elements. This is also a list that the user might not be familiar with, so a search would help the user find the correct element.
- Is the auto-complete component enough? Altinn/app-frontend-react#193
- Do we need heavier search functionality? (Search based on more elements than just a list of "næringskoder")
- Do we need a tree structure component, so the user can get an overview of how "næringskoder" is set up. [Example here](https://data.brreg.no/oppgaveregisteret/oppslag)

**Based on "kommune" and "næringskode" calculate relevant information.**
The user is prompted to select what "kommune" they are going to do business in and in what "næringskode" based on this information we have to get information about that "næringskode" inside that "kommune" and present it for the user. 
- We need a way to show it, this might be handled by in the info-panel mentioned earlier
- Do we have to connect this to any open data sources? 

**Create an URL with parameters from the form**
Create an URL based on input from the user and present it at the recommendation page

**Traffic light component**
Based on the input of the user we will give them a recommendation if they should start their business. To handle this we need to give each answer a value and have some kind of controller that calculates what output they should be given in the summary page. We should also look into how we can present the answer in a way that it is clear for the user that it is based on their input trough the application.

**Application without log in**
Earlier e-guides have been made with no log in functionality. This makes it easier for the user to just start going trough the guide. The downside is that we can not fill out information from their profile.  Altinn/app-frontend-react#131

**Comment by andreas-didriksen** [comment]
Stateless app do not support Tracks. Oppstartsveileder must either use Dynamics instead of Tracks or Stateless app must support Tracks  https://github.com/Altinn/altinn-studio/issues/8347

**Comment by andreas-didriksen** [comment]
Print without login. https://github.com/Altinn/altinn-studio/issues/7499
