### ISSUE TITLE
Månedsrapport biomasse FD-0001

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/app-migration#73]
## Innledning

 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** |2382  |
| **Tjenesteutgavekode**  | 3 |
| **Tjenestetype**  | Innsending  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | Web Service  |
 

## Generelle egenskaper
Skjemaet har en veldig bred tabell. Så det er ikke sikkert tabellen fungerer i 3.0

#### Hvordan benyttes Tjenesten?
- [ ] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
![image](https://user-images.githubusercontent.com/75472603/178971925-6b07404b-efea-4205-ab6c-26eeee101d31.png)
![image](https://user-images.githubusercontent.com/75472603/178971954-45f86b05-944f-400c-9687-6176fba63901.png)
![image](https://user-images.githubusercontent.com/75472603/178971974-3c101f2b-ec2e-45d5-82af-f9101e1a7af2.png)

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/fiskeridirektoratet/manedsrapport-biomasse/  |
| TUL  | http://tul-spwb.ai.basefarm.net/sites/fd/FD-0001_2010/Biomasse-2022/default.aspx  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=2&ServiceCode=2382&Oselect=true |
| Altinn 2.0 (prod)  | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=3&ServiceCode=2382&Oselect=true |

- XSD: _Last opp XSD her (i .zip-format)_
[Fiskeridirektoratet_FD-0001MaanedsrapportBiomasseLakselus_M_2021-01-05_6107_46232_SERES.zip](https://github.com/Altinn/apps-backlog/files/9110438/Fiskeridirektoratet_FD-0001MaanedsrapportBiomasseLakselus_M_2021-01-05_6107_46232_SERES.zip)

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by andreas-didriksen** [comment]
Repeterende gruppe komponenten fungerer ikke helt for skjemaet.
![image](https://user-images.githubusercontent.com/75472603/185078237-a56c5733-a65f-484c-b7e4-1625fd6a903c.png)

**Comment by elwal** [comment]
Fiskeridirektoratet utvikler denne appen selv.
