### ISSUE TITLE
KRT-1228-Brudd på gjenopprettingsindikatorer

### ISSUE THREAD

**Issue by stalehalden** [Altinn/app-migration#79]
## Innledning

| Beskrivelse av tjenesten      | Brudd på gjenopprettingindikatorer. Dette er en åpen rapportering |
| ----------------------------- | --------------------------- |
| **Volum**                     | Få innrappoteringer i året    |
| **Planlagt produksjonssatt**  | 01.09.2022                  |

## Generelle egenskaper
Åpent skjema med vedleggsrapportering. Kun foretak som rapporterer, ingen privatpersoner.
Skjemaet skal ikke til Sentralfag
Skjema skal overføres Websak

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

## Behov for funksjonalitet
Noen skjulte felter og litt preutfylling

**Comment by elwal** [comment]
Tjeneste produksjonssatt 9. september 2022.
