### ISSUE TITLE
KRT-1226-Gjenopprettingsplaner

### ISSUE THREAD

**Issue by stalehalden** [Altinn/app-migration#80]
## Innledning
Skjemaet benyttes til rapportering om gjenopprettingsplaner for banker, kredittforetak, holdingforetak i finanskonsern og finansieringsforetak som inngår i finanskonsern. Vedleggsrapportering.

| **Volum**                     | Årlig, kommer inn løpende gjennom året på samme måte som ICAAP  |
| **Planlagt produksjonssatt**  | 01.09.2022                 |

## Generelle egenskaper
Skjema skal overføres til Websak med kode 304.11
Skal ikke til rapporteringsregisteret
Må ha vedlegg

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året, hendelsesbasert._

## Behov for funksjonalitet
Abonnementsskjema.  Noen skjulte felter

## Lenker og filer

| Område            | Lenke     |
| ----------------- | --------- |
| Altinn Studio     |           |
| Altinn 3.0 (test) |           |

**Comment by elwal** [comment]
Tjeneste produksjonssatt 9. september 2022.
