### ISSUE TITLE
KRT-1030-Sletting av autorisasjon som regnskapsfører

### ISSUE THREAD

**Issue by stalehalden** [Altinn/app-migration#81]
## Innledning
Åpent skjema med kobling til Websak og Sfag

| **Volum**                     | Volum2021 var på 100  |
| **Planlagt produksjonssatt**  | _dd.mm.åå_ |

## Generelle egenskaper
Skjema sperres for vedlegg
Skjema skal overføres til Websak
Det opprettes en sak i WS, skjemakopi legges inn som journalpost 1. Offentlighetsvurdering settes til blank (Off). Arkivkode og tittel hentes fra kodene i skjemaet.
Det gjøres en sjekk av personen mot Sentralfag, hvis det er en feilsituasjon - personen finnes ikke i Sentralfag eller har ikke autorisasjon som regnskapsfører – varsel sendes pr mail fagavd (MAL og UHA) for manuell håndtering. 
Status på konsesjonen settes til Opphørt i Sentralfag.
Fra-dato settes til dato oppgitt i skjemaet.

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

Åpent skjema gjennom hele året

## Behov for funksjonalitet
> Fyll ut

## Lenker og filer

| Område            | Lenke     |
| ----------------- | --------- |
| Altinn Studio     |           |
| Altinn 3.0 (test) |           |

**Comment by elwal** [comment]
Produksjonssatt 06.12.22
