### ISSUE TITLE
KRT-1036-Opphør av revisjonsvirksomhet i enkeltpersonforetak

### ISSUE THREAD

**Issue by stalehalden** [Altinn/app-migration#85]
## Innledning

 
 | Beskrivelse av tjenesten | Skjema gjelder opphør av revisjonsvirksomhet i enkeltpersonforetak. Åpent skjema
| ------------- | ------------- |
| **Tjenestekode** | _Legg inn tjenestekode (ServiceCode)_  |
| **Tjenesteutgavekode**  |  _Legg inn tjenesteutgavekode (ServiceEditionCode)_ |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  |Få innleveringer per år, 2021 viste 25  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

Åpent skjema gjennom hele året.  Lite kompleksitet

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 06.12.22
