### ISSUE TITLE
KRT-1037-Sletting av registrering som forsikringsagent eller forsikringsmegler 		

### ISSUE THREAD

**Issue by stalehalden** [Altinn/app-migration#86]
## Innledning

 
 | Beskrivelse av tjenesten | Skjema for å slette registrering som forsikringsagent eller forsikringsmegler
| ------------- | ------------- |
| **Tjenestekode** | 5776  |
| **Tjenesteutgavekode**  | 1 |

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

Åpent skjema gjennom hele året, må dekke nivå 0 pålogging med overføring til Websak

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://www.altinn.no/skjemaoversikt/finanstilsynet/forsikringsforetakets-meldeplikt-ved-opphor-av-avtale-om-forsikringsformidling/ |
| TUL  | http://tul.altinn.cloud/sites/krt/KRT-1037/Utgave1/default.aspx |
| Altinn 2.0 (test)  | https://tt02.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5776 |
| Altinn 2.0 (prod)  | https://www.altinn.no/Pages/ServiceEngine/Start/StartService.aspx?ServiceEditionCode=1&ServiceCode=5776  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.studio/repos/krt/krt-1037a-1 |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Prodsatt 8.12.2023
