### ISSUE TITLE
KRT-1021-Omsetningstall for revisjonsforetak

### ISSUE THREAD

**Issue by stalehalden** [Altinn/app-migration#87]
## Innledning

 
 | Beskrivelse av tjenesten | Finanstilsynet foretar hvert år en utlikning for å fordele kostnader. I de årene hvor KRT-1002 leveres får vi inn nødvendige tall via skjemaene, men i årene i mellom er det nødvendig å hente inn tall på annen måte. I de senere årene henter vi inn tall fra dette skjemaet for alle år, også når 1002 leveres.
| ------------- | ------------- |
| **Tjenestekode** | _Legg inn tjenestekode (ServiceCode)_  |
| **Tjenesteutgavekode**  |  _Legg inn tjenesteutgavekode (ServiceEditionCode)_ |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | >500 innleveringer per år |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Har tjenesten frister eller andre egenskaper?
- [ ] Ja
- [x] Nei

Abonnementsliste(ikke åpent skjema) med ingen kobling til Websak eller sfag

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Behov for funksjonalitet
> Fyll ut

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by elwal** [comment]
Produksjonssatt 21.12.22
